name: "Inferno"
description: "A vote listener designed to encourage people to consistently vote."
main: "com.firestartermc.inferno.Inferno"
author: "Firestarter Minecraft Servers"
website: "https://firestartermc.com"
version: "1.2"
api-version: "1.16"

depend:
  - "Kerosene"
  - "HolographicDisplays"
  - "Votifier"
  - "ShopGUIPlus"

commands:
  inferno:
    description: "Base Inferno administrative command."
    usage: "/<command> <addstreak/addtokens/sendvote>"
  vote:
    description: "Vote for the server."
  streak:
    description: "View your current voting streak."