name: Inferno
version: 2.1
author: TechToolbox (@nkomarn)
main: com.firestartermc.inferno.Inferno
description: A vote listener designed to encourage people to consistently vote.
website: https://firestartermc.com/opensource
api-version: 1.16
depend: ['Kerosene', 'HolographicDisplays', 'Votifier']

commands:
  streak:
    description: "View your voting streak."
  addstreak:
    description: "Adds streak levels to a player."
    permission: "inferno.addstreak"
  sendvote:
    description: "Sends a fake vote with a username."
    permission: "inferno.sendvote"

permissions:
  inferno.addstreak:
    default: op
  inferno.sendvote:
    default: op